services:
  - type: web
    name: attendance-bot
    env: docker
    region: singapore
    plan: starter # A starter plan is required because free tier does not support persistent disks!
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 5000
      - key: HEADLESS
        value: True
